// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace STEMsalariesModelBuilder
{
    public partial class MLModelBuildermbconfig
    {
        /// <summary>
        /// model input class for MLModelBuildermbconfig.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"AnualCompensation")]
            public float AnualCompensation { get; set; }

            [ColumnName(@"Company")]
            public string Company { get; set; }

            [ColumnName(@"Title")]
            public string Title { get; set; }

            [ColumnName(@"YearsExperience")]
            public float YearsExperience { get; set; }

            [ColumnName(@"YearsCompany")]
            public float YearsCompany { get; set; }

            [ColumnName(@"Gender")]
            public string Gender { get; set; }

            [ColumnName(@"Location")]
            public string Location { get; set; }

            [ColumnName(@"Race")]
            public string Race { get; set; }

            [ColumnName(@"Education")]
            public string Education { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModelBuildermbconfig.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModelBuildermbconfig.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
